"""Package-level public API for the radiative-transfer helper modules."""

from .pf_fitting import (
    PFData,
    evaluate_PF_from_fit_result,
    evaluate_PF_from_polynomial,
    fit_and_plot_PF,
    get_PF_at_angle_fast,
    load_IQ_inp,
    model_func_PF,
    read_single_inp as read_pf_inp,
)
from .stokes_i_fitting import (
    StokesIData,
    evaluate_I_from_fit_result,
    evaluate_I_from_polynomial,
    fit_and_plot_I,
    get_I_at_angle_fast,
    load_I_only_inp,
    make_model_func_fixed_mu,
    read_single_inp as read_stokes_i_inp,
    stokes_i_model_with_mu,
)
from .stokes_interpolation import (
    StokesInterpolationContext,
    analytic_thin_I_scalar,
    collect_emergent_tables,
    emergent_polarization,
    emergent_stokes,
    interpolate_stokes,
    load_emergent_file,
    load_stokes_context,
    setup_tables,
)

__all__ = [
    "PFData",
    "StokesIData",
    "StokesInterpolationContext",
    "analytic_thin_I_scalar",
    "collect_emergent_tables",
    "emergent_polarization",
    "emergent_stokes",
    "evaluate_I_from_fit_result",
    "evaluate_I_from_polynomial",
    "evaluate_PF_from_fit_result",
    "evaluate_PF_from_polynomial",
    "fit_and_plot_I",
    "fit_and_plot_PF",
    "get_I_at_angle_fast",
    "get_PF_at_angle_fast",
    "interpolate_stokes",
    "load_emergent_file",
    "load_I_only_inp",
    "load_IQ_inp",
    "load_stokes_context",
    "make_model_func_fixed_mu",
    "model_func_PF",
    "read_pf_inp",
    "read_stokes_i_inp",
    "setup_tables",
    "stokes_i_model_with_mu",
]
